global_frame: map
rolling_window: true
track_unknown_space: true

plugins:
  - {name: obstacles_kinect,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
